export const initialEventFormValues = {
  clientDetails: { clientName: '', email: '', phoneNumber: '', address: '', postCode: '' },
  events: [
    {
      eventName: '',
      eventType: '',
      eventDate: null,
      guestCount: '',
      venue: '',
      postCode: '',
      notesForEvent: '',
      services: {
        stageDecoration: false,
        catering: false,
        transportation: false,
        accommodation: false,
        venueBooking: false,
        venueFloorPlanning: false,
        mehandiHaldi: false,
        bridalMakeup: false,
        groomsMakeup: false,
        photographyVideography: false,
        saveTheDate: false,
        cardDesignPrinting: false,
        outfitDesign: false,
        honeymoonPackage: false,
        pandalSetup: false,
        eventFurniture: false,
        eventUtensils: false,
      },
      addOns: {
        dj: false,
        droneCoverage: false,
        liveBand: false,
        liveStreaming: false,
        lcdScreens: false,
        laserLightShow: false,
        fireworks: false,
        photoBooth: false,
        welcomeGirls: false,
        welcomeCanvasFrame: false,
        welcomeArch: false,
        partyCake: false,
        bouquetHaram: false,
        valetParking: false,
        eventInsurance: false,
        securityServices: false,
        socialMediaCoverage: false,
        alchoholLicence: false,
      },
    },
  ],
};
