export const formStepsConfig = [
  {
    id: 1,
    subtitle: 'Start with basics, then add services like decorations and catering.',
    sections: [
      {
        title: 'Client Information',
        section: 'clientDetails',
        fields: [
          {
            name: 'clientName',
            label: 'Client name',
            type: 'text',
            placeholder: 'e.g., John Doe',
          },
          {
            name: 'email',
            label: 'Email',
            type: 'email',
            placeholder: 'e.g., john@example.com',
          },
          {
            name: 'phoneNumber',
            label: 'Phone number',
            type: 'tel',
            placeholder: 'e.g., +91 98765 43210',
          },
          {
            name: 'address',
            label: 'Address',
            type: 'text',
            placeholder: 'e.g., Mumbai, Maharashtra',
          },
          {
            name: 'postCode',
            label: 'Post Code',
            type: 'text',
            placeholder: 'e.g., 400001',
          },
        ],
      },
    ],
    actions: {
      secondary: [{ label: 'Save draft', action: 'draft' }],
      primary: { label: 'Next: Event Details', action: 'next' },
    },
  },
  {
    id: 2,
    subtitle: 'Add one or more events (e.g., Wedding, Reception, Mehandi)',
    sections: [
      {
        title: 'Event Details',
        section: 'events',
        type: 'multiple-events',
        fields: [
          {
            name: 'eventName',
            label: 'Event name',
            type: 'text',
            placeholder: 'e.g., Wedding Reception',
          },
          {
            name: 'eventType',
            label: 'Event type',
            type: 'select',
            placeholder: 'Select event type',
            options: [
              { value: 'wedding', label: 'Wedding' },
              { value: 'destinationWedding', label: 'Destination Wedding' },
              { value: 'reception', label: 'Reception' },
              { value: 'engagement', label: 'Engagement' },
              { value: 'birthday', label: 'Birthday' },
              { value: 'corporate', label: 'Corporate' },
              { value: 'other', label: 'Other' },
            ],
          },
          {
            name: 'eventDate',
            label: 'Date & time',
            type: 'date',
            placeholder: 'e.g., 20 Feb 2026, 5:00 PM',
            showTimeSelect: true,
            minDate: new Date(),
            dateFormat: 'dd MMM yyyy, h:mm aa',
          },
          {
            name: 'guestCount',
            label: 'Guest count',
            type: 'text',
            placeholder: 'e.g., 250',
          },
          {
            name: 'venue',
            label: 'Venue',
            type: 'text',
            placeholder: 'Venue name + address',
            fullWidth: true,
          },
          { name: 'postCode', label: 'Post Code', type: 'text', placeholder: 'e.g., 400001' },
          {
            name: 'notesForEvent',
            label: 'Additional notes for services and add-ons',
            type: 'textarea',
            placeholder:
              'Enter any additional notes for services (e.g., specific themes, dietary preferences)',
            fullWidth: true,
          },
        ],
        servicesFields: [
          {
            name: 'destinationWedding',
            label: 'Destination Wedding',
            description: 'Wedding held at a location away from the couple’s hometown',
            type: 'checkbox',
          },
          {
            name: 'stageDecoration',
            label: 'Stage Decoration',
            description: 'Backdrop, flowers & lighting',
            type: 'checkbox',
          },
          {
            name: 'catering',
            label: 'Catering',
            description: 'Food & beverages with serving staff',
            type: 'checkbox',
          },
          {
            name: 'transportation',
            label: 'Transportation',
            description: 'Guest & couple transport',
            type: 'checkbox',
          },
          {
            name: 'accommodation',
            label: 'Accommodation',
            description: 'Guest & couple accommodation arrangements',
            type: 'checkbox',
          },
          {
            name: 'venueFloorPlanning',
            label: 'Venue Floor Planning',
            description: 'Layout and design of the event venue, including seating arrangements',
            type: 'checkbox',
          },
          {
            name: 'venueBooking',
            label: 'Venue Booking',
            description: 'Booking and reservation of the event venue',
            type: 'checkbox',
          },
          {
            name: 'mehandiHaldi',
            label: 'Mehandi or Haldi',
            description: 'Traditional ceremonies',
            type: 'checkbox',
          },
          {
            name: 'bridalMakeup',
            label: 'Bridal Makeup',
            description: 'Professional makeup services for the bride',
            type: 'checkbox',
          },
          {
            name: 'groomsMakeup',
            label: 'Grooms Makeup',
            description: 'Professional makeup services for the grooms',
            type: 'checkbox',
          },
          {
            name: 'photographyVideography',
            label: 'Photography & Videography',
            description: 'Professional coverage',
            type: 'checkbox',
          },
          {
            name: 'saveTheDate',
            label: 'Save The Date',
            description: 'Announcement',
            type: 'checkbox',
          },
          {
            name: 'cardDesignPrinting',
            label: 'Card Design & Printing',
            description: 'Invitation cards',
            type: 'checkbox',
          },
          {
            name: 'outfitDesign',
            label: 'Outfit Design',
            description: 'Custom outfits',
            type: 'checkbox',
          },
          {
            name: 'honeymoonPackage',
            label: 'Honeymoon Destination Planning',
            description: 'Travel arrangements',
            type: 'checkbox',
          },
          {
            name: 'pandalSetup',
            label: 'Pandal Setup',
            description:
              'Event structures like shamianas, fibre sheet pandal, germen tent and decoration',
            type: 'checkbox',
          },
          {
            name: 'eventFurniture',
            label: 'Event Furniture',
            description: 'Furniture arrangements for the event like chairs, tables, sofas, etc.',
            type: 'checkbox',
          },
          {
            name: 'eventUtensils',
            label: 'Event Utensils',
            description:
              'Utensil arrangements for the event like plates, glasses, cutlery,vessels etc.',
            type: 'checkbox',
          },
        ],
        addOnsFields: [
          {
            name: 'dj',
            label: 'DJ',
            description: 'Music and entertainment',
            type: 'checkbox',
          },
          {
            name: 'droneCoverage',
            label: 'Drone Coverage',
            description: 'Aerial photography and videography',
            type: 'checkbox',
          },
          {
            name: 'liveBand',
            label: 'Live Band',
            description: 'Music and entertainment',
            type: 'checkbox',
          },
          {
            name: 'liveStreaming',
            label: 'Live Streaming',
            description: 'Broadcast your event live to remote guests',
            type: 'checkbox',
          },
          {
            name: 'lcdScreens',
            label: 'LCD Screens',
            description: 'Display screens for event visuals and live feed',
            type: 'checkbox',
          },
          {
            name: 'laserLightShow',
            label: 'Laser Light Show',
            description: 'Music and entertainment',
            type: 'checkbox',
          },
          {
            name: 'fireworks',
            label: 'Fireworks',
            description: 'Guest & couple entertainment',
            type: 'checkbox',
          },
          {
            name: 'photoBooth',
            label: 'Photo Booth',
            description: 'Fun photo sessions',
            type: 'checkbox',
          },
          {
            name: 'welcomeCanvasFrame',
            label: 'Welcome Canvas Frame',
            description: 'Personalized canvas frame for guest welcome',
            type: 'checkbox',
          },
          {
            name: 'welcomeArch',
            label: 'Welcome Arch',
            description: 'Personalized arch for guest welcome',
            type: 'checkbox',
          },
          {
            name: 'welcomeGirls',
            label: 'Welcome Girls',
            description: 'Traditional welcome service',
            type: 'checkbox',
          },
          {
            name: 'partyCake',
            label: 'Party Cake',
            description: 'Celebration cake service',
            type: 'checkbox',
          },
          {
            name: 'bouquetHaram',
            label: 'Bouquet Haram',
            description: 'Floral arrangements for the event',
            type: 'checkbox',
          },
          {
            name: 'valetParking',
            label: 'Valet Parking',
            description: 'Convenient parking service',
            type: 'checkbox',
          },
          {
            name: 'eventInsurance',
            label: 'Event Insurance',
            description: 'Protect your event with insurance coverage',
            type: 'checkbox',
          },
          {
            name: 'securityServices',
            label: 'Security Services',
            description: 'Ensure safety with professional security personnel',
            type: 'checkbox',
          },
          {
            name: 'socialMediaCoverage',
            label: 'Social Media Coverage',
            description: 'Live updates and posts on social media platforms',
            type: 'checkbox',
          },
          {
            name: 'alchoholLicence',
            label: 'Alcohol Licence',
            description: 'Permit for serving alcohol at the event',
            type: 'checkbox',
          },
        ],
      },
    ],
    actions: {
      secondary: [
        { label: 'Save draft', action: 'draft' },
        { label: 'Back: Client Information', action: 'back' },
      ],
      primary: { label: 'Next: Review', action: 'next' },
    },
  },
  {
    id: 3,
    subtitle: 'Review & Submit',
    sections: [
      {
        title: 'Review & Submit',
        subtitle: 'Review your event details and submit your request',
        type: 'review',
        fields: [{ type: 'review' }],
      },
    ],
    actions: {
      secondary: [
        { label: 'Save draft', action: 'draft' },
        { label: 'Back: Event Details', action: 'back' },
      ],
      primary: { label: 'Submit', action: 'submit' },
    },
  },
];
