// Configuration for service and addon detail fields
export const serviceDetailFields = {
  destinationWedding: [
    {
      name: 'destinationLocation',
      label: 'Destination Location',
      type: 'text',
      placeholder: 'City, Country',
      required: true,
    },
    {
      name: 'weddingVenueType',
      label: 'Wedding Venue Type',
      type: 'text',
      placeholder: 'e.g., beach, garden, heritage site, hotel, resort, house boat etc.',
      required: true,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, wording...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  stageDecoration: [
    {
      name: 'stageProvidedInVenue',
      label: 'Is stage provided in the venue?',
      type: 'select',
      placeholder: 'Select an option',
      options: [
        { value: 'true', label: 'Yes' },
        { value: 'false', label: 'No' },
        { value: 'needToCheck', label: 'Need to check' },
      ],
    },
    {
      name: 'theme',
      label: 'Theme',
      type: 'select',
      placeholder: 'Select theme',
      options: [
        { value: 'traditional', label: 'Traditional' },
        { value: 'floral', label: 'Floral' },
        { value: 'modern', label: 'Modern' },
        { value: 'balloon', label: 'Balloon' },
        { value: 'mixed', label: 'Mixed' },
      ],
    },
    {
      name: 'decorationPhotos',
      label: 'Select Decoration',
      type: 'gallery-select',
      galleryPath: '/images/decorations',
      helperText: 'Click to select decoration styles from gallery',
      required: false,
    },
    {
      name: 'colorScheme',
      label: 'Color Scheme',
      type: 'text',
      placeholder: 'e.g., Red & Gold, Pink & White',
      required: false,
    },
    {
      name: 'seatingArrangement',
      label: 'Seating Arrangement',
      type: 'select',
      placeholder: 'Select seating arrangement',
      options: [
        { value: 'sofa', label: 'Sofa' },
        { value: 'diwan', label: 'Diwan' },
        { value: 'simhasanam', label: 'Simhasanam' },
        { value: 'oonjal', label: 'Oonjal' },
        { value: 'custom', label: 'Custom' },
      ],
    },
    {
      name: 'numberOfSeats',
      label: 'Number of Seats',
      type: 'select',
      placeholder: 'Select number of seats',
      options: [
        { value: 1, label: '1 seat' },
        { value: 2, label: '2 seats' },
        { value: 3, label: '3 seats' },
        { value: 4, label: '4 seats' },
        { value: 5, label: '5 seats' },
      ],
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Add any specific requirements...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹50,000',
      required: false,
    },
  ],
  catering: [
    {
      name: 'foodServingInVenue',
      label: 'Menu in the venue',
      type: 'nested-form',
      nestedArrayKey: 'menu',
      nestedArrayLabel: 'Menu',
      fields: [
        {
          name: 'servingTime',
          label: 'Serving Time',
          type: 'select',
          placeholder: 'Select serving time',
          options: [
            { value: 'breakfast', label: 'Breakfast' },
            { value: 'lunch', label: 'Lunch' },
            { value: 'dinner', label: 'Dinner' },
            { value: 'eveSnack', label: 'Evening Snack' },
            { value: 'brunch', label: 'Brunch' },
            { value: 'hiTea', label: 'Hi-Tea' },
          ],
          required: true,
        },
        {
          name: 'cuisineType',
          label: 'Cuisine Type',
          type: 'select',
          placeholder: 'Select cuisine type',
          options: [
            { value: 'buffet', label: 'Buffet' },
            { value: 'southIndianSadhya', label: 'South Indian Sadhya' },
            { value: 'southIndian', label: 'South Indian Dish' },
            { value: 'northIndianThali', label: 'North Indian Thali' },
            { value: 'northIndian', label: 'North Indian Dish' },
            { value: 'plated', label: 'Plated Service' },
            { value: 'liveCounter', label: 'Live Counter' },
            { value: 'continental', label: 'Continental' },
            { value: 'chinese', label: 'Chinese' },
            { value: 'italianMexican', label: 'Italian/Mexican' },
            { value: 'mixed', label: 'Mixed Cuisine' },
          ],
          required: true,
        },
        {
          menu: [
            {
              name: 'menuItem',
              label: 'Menu Item',
              type: 'text',
              placeholder: 'Dish name',

              required: false,
            },
            {
              name: 'menuItemType',
              label: 'Menu Item Type',
              type: 'select',
              placeholder: 'Type of dish, e.g., appetizer, main course...',
              options: [
                { value: 'appetizer', label: 'Appetizer' },
                { value: 'starter', label: 'Starter' },
                { value: 'mainCourse', label: 'Main Course' },
                { value: 'sideDish', label: 'Side Dish' },
                { value: 'dessert', label: 'Dessert' },
                { value: 'beverage', label: 'Beverage' },
              ],
              required: false,
            },
            {
              name: 'menuItemDiet',
              label: 'Menu Item Diet',
              type: 'select',
              placeholder: 'Diet of dish, e.g., vegetarian, non-vegetarian...',
              options: [
                { value: 'vegetarian', label: 'Vegetarian' },
                { value: 'nonVegetarian', label: 'Non-Vegetarian' },
                { value: 'vegan', label: 'Vegan' },
                { value: 'eggegitarian', label: 'Eggetarian' },
                { value: 'glutenFree', label: 'Gluten-Free' },
                { value: 'dairy', label: 'Dairy' },
              ],
              required: false,
            },
            {
              name: 'liveCounterMenuItem',
              label: 'Live Counter Menu Item',
              type: 'text',
              placeholder: 'yes/no/need to check',
              required: false,
            },
          ],
        },
        {
          name: 'servers',
          label: 'Serving Staff',
          type: 'select',
          placeholder: 'Select serving staff requirement',
          options: [
            { value: 'true', label: 'Yes' },
            { value: 'false', label: 'No' },
          ],
          required: false,
        },
      ],
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Dietary restrictions, menu preferences...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹100,000',
      required: false,
    },
  ],
  transportation: [
    {
      name: 'vehicleDetails',
      label: 'Vehicle Details',
      type: 'array',
      itemLabel: 'Vehicle',
      fields: [
        {
          name: 'vehicleType',
          label: 'Vehicle Type',
          type: 'select',
          placeholder: 'Select vehicle type requirement',
          options: [
            { value: 'sedan', label: 'Sedan - up to 5 seats' },
            { value: 'bus', label: 'Bus - up to 40 seats' },
            { value: 'van', label: 'Van - up to 18 seats' },
            { value: 'suv', label: 'SUV - up to 5 seats' },
            { value: 'luxurySedan', label: 'Luxury Sedan Car' },
            { value: 'limousine', label: 'Limousine' },
            { value: 'muv', label: 'MUV - up to 7 seats' },
          ],
          required: false,
        },
        {
          name: 'numberOfVehicles',
          label: 'Number of Vehicles',
          type: 'text',
          placeholder: 'e.g., 2 cars, 1 bus',
          required: false,
        },
        {
          name: 'driverRequired',
          label: 'Driver Required',
          type: 'select',
          placeholder: 'Select driver requirement',
          options: [
            { value: 'true', label: 'Yes' },
            { value: 'false', label: 'No' },
          ],
          required: false,
        },
        {
          name: 'vehiclePickupDropTiming',
          label: 'Vehicle Required Date & Time',
          type: 'datepicker',
          placeholder: 'Select date and time',
          showTimeSelect: true,
          minDate: new Date(),
          dateFormat: 'dd MMM yyyy, h:mm aa',
        },
      ],
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Route details, pickup/drop locations...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹30,000',
      required: false,
    },
  ],
  accommodation: [
    {
      name: 'accommodationDetails',
      label: 'Accommodation Details',
      type: 'array',
      itemLabel: 'Accommodation',
      fields: [
        {
          name: 'accommodationType',
          label: 'Accommodation Type',
          type: 'select',
          placeholder: 'e.g., airbnb, hotel, resort',
          options: [
            { value: 'airbnb', label: 'Airbnb' },
            { value: 'hotel3Star', label: 'Hotel 3 Star' },
            { value: 'hotel4Star', label: 'Hotel 4 Star' },
            { value: 'hotel5Star', label: 'Hotel 5 Star' },
            { value: 'resort', label: 'Resort' },
          ],
          required: false,
        },
        {
          name: 'roomType',
          label: 'Room Type',
          type: 'text',
          placeholder: 'e.g., Single, Double, Suite',
          required: false,
        },
        {
          name: 'guestsStaying',
          label: 'Number of Guests Staying',
          type: 'text',
          placeholder: 'e.g., 2 adults, 1 child',
          required: false,
        },
        {
          name: 'travelArrangementRequired',
          label: 'Travel Arrangement Required',
          type: 'select',
          placeholder: 'e.g., Yes, No, Need to check',
          options: [
            { value: 'true', label: 'Yes' },
            { value: 'false', label: 'No' },
            { value: 'needToCheck', label: 'Need to check' },
          ],
          required: false,
        },
        {
          name: 'checkInDateTime',
          label: 'Check-In Date & Time',
          type: 'datepicker',
          placeholder: 'Select date and time',
          showTimeSelect: true,
          minDate: new Date(),
          dateFormat: 'dd MMM yyyy, h:mm aa',
        },
        {
          name: 'checkOutDateTime',
          label: 'Check-Out Date & Time',
          type: 'datepicker',
          placeholder: 'Select date and time',
          showTimeSelect: true,
          minDate: new Date(),
          dateFormat: 'dd MMM yyyy, h:mm aa',
        },
      ],
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Add any specific requirements...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹50,000',
      required: false,
    },
  ],
  venueBooking: [
    {
      name: 'venueBookingDetails',
      label: 'Venue Booking Details',
      type: 'array',
      itemLabel: 'Venue',
      fields: [
        {
          name: 'venueOption1',
          label: 'Venue Option 1',
          type: 'text',
          placeholder: 'Venue name and address if you have one in mind',
          required: false,
        },
        {
          name: 'venueOption2',
          label: 'Venue Option 2',
          type: 'text',
          placeholder: 'Venue name and address if you have one in mind',
          required: false,
        },
        {
          name: 'venueType',
          label: 'Venue Type',
          type: 'select',
          placeholder: 'e.g., hall, auditorium, convention center',
          options: [
            { value: 'hall', label: 'Hall' },
            { value: 'auditorium', label: 'Auditorium' },
            { value: 'conventionCenter', label: 'Convention Center' },
            { value: 'resort', label: 'Resort' },
          ],
          required: false,
        },
        {
          name: 'checkInDateTime',
          label: 'Check-In Date & Time',
          type: 'datepicker',
          placeholder: 'Select date and time',
          showTimeSelect: true,
          minDate: new Date(),
          dateFormat: 'dd MMM yyyy, h:mm aa',
        },
        {
          name: 'checkOutDateTime',
          label: 'Check-Out Date & Time',
          type: 'datepicker',
          placeholder: 'Select date and time',
          showTimeSelect: true,
          minDate: new Date(),
          dateFormat: 'dd MMM yyyy, h:mm aa',
        },
      ],
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Add any specific requirements...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹50,000',
      required: false,
    },
  ],
  venueFloorPlanning: [
    {
      name: 'seatingArrangement',
      label: 'Seating Arrangement',
      type: 'select',
      placeholder: 'e.g., theatre style, banquet style, classroom style',
      options: [
        { value: 'theatreStyle', label: 'Theatre Style' },
        { value: 'banquetStyle', label: 'Banquet Style' },
        { value: 'classroomStyle', label: 'Classroom Style' },
        { value: 'uShape', label: 'U-Shape' },
        { value: 'boardroomStyle', label: 'Boardroom Style' },
        { value: 'hollowSquare', label: 'Hollow Square' },
        { value: 'cabaret', label: 'Cabaret' },
        { value: 'mixed', label: 'Mixed Arrangement' },
        { value: 'custom', label: 'Custom Arrangement' },
      ],
      required: false,
    },
    {
      name: 'chairCover',
      label: 'Chair Cover',
      type: 'text',
      placeholder: 'e.g., yes, no, need to check',
      required: false,
    },
    {
      name: 'chairCoverColor',
      label: 'Chair Cover Color',
      type: 'text',
      placeholder: 'e.g., red, blue, white',
      required: false,
    },
    {
      name: 'chairSashColor',
      label: 'Chair Sash Color',
      type: 'text',
      placeholder: 'e.g., red, blue, white',
      required: false,
    },
    {
      name: 'chairSashType',
      label: 'Chair Sash Type',
      type: 'text',
      placeholder: 'e.g., satin, organza, silk',
      required: false,
    },
    {
      name: 'tableCover',
      label: 'Table Cover',
      type: 'text',
      placeholder: 'e.g., yes, no, need to check',
      required: false,
    },
    {
      name: 'tableCoverColor',
      label: 'Table Cover Color',
      type: 'text',
      placeholder: 'e.g., red, blue, white',
      required: false,
    },
    {
      name: 'tableTopFlowerArrangement',
      label: 'Table Top Flower Arrangement',
      type: 'text',
      placeholder: 'e.g., red, blue, white',
      required: false,
    },
    {
      name: 'ceilingDecoration',
      label: 'Ceiling Decoration',
      type: 'text',
      placeholder: 'e.g., yes, no, need to check',
      required: false,
    },
    {
      name: 'ceilingDecorationType',
      label: 'Ceiling Decoration Type',
      type: 'text',
      placeholder: 'e.g., fabric draping, fairy lights, chandeliers',
      required: false,
    },
    {
      name: 'ceilingDecorationThemeColor',
      label: 'Ceiling Decoration Theme Color',
      type: 'text',
      placeholder: 'e.g., red, blue, white',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Add any specific requirements...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹50,000',
      required: false,
    },
  ],
  mehandiHaldi: [
    {
      name: 'ceremonyType',
      label: 'Ceremony Type',
      type: 'text',
      placeholder: 'e.g., Mehandi, Haldi, Both',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Special requirements, timing...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹25,000',
      required: false,
    },
  ],
  bridalMakeup: [
    {
      name: 'makeupType',
      label: 'Makeup Type',
      type: 'text',
      placeholder: 'e.g., Bridal, Bridal Party',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Special requirements, timing...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹25,000',
      required: false,
    },
  ],
  groomsMakeup: [
    {
      name: 'makeupType',
      label: 'Makeup Type',
      type: 'text',
      placeholder: 'e.g., Bridal, Bridal Party',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Special requirements, timing...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹25,000',
      required: false,
    },
  ],
  photographyVideography: [
    {
      name: 'serviceType',
      label: 'Service Type',
      type: 'text',
      placeholder: 'e.g., Photography, Videography, Both',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., Full day, Half day',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Style preferences, special shots required...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹80,000',
      required: false,
    },
  ],
  saveTheDate: [
    {
      name: 'format',
      label: 'Format',
      type: 'text',
      placeholder: 'e.g., Digital, Printed, Both',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, distribution details...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹10,000',
      required: false,
    },
  ],
  cardDesignPrinting: [
    {
      name: 'cardType',
      label: 'Card Type',
      type: 'text',
      placeholder: 'e.g., Traditional, Modern, Designer',
      required: false,
    },
    {
      name: 'quantity',
      label: 'Quantity',
      type: 'text',
      placeholder: 'e.g., 500 cards',
      required: true,
    },
    {
      name: 'brideName',
      label: 'Bride Name',
      type: 'text',
      placeholder: 'e.g., Jane Doe',
      required: true,
    },
    {
      name: 'brideParentsNames',
      label: 'Bride Parents Names',
      type: 'text',
      placeholder: 'e.g., Mr. and Mrs. Smith',
      required: true,
    },
    {
      name: 'brideAddress',
      label: 'Bride Address',
      type: 'text',
      placeholder: 'e.g., 123 Main St, City, Country',
      required: true,
    },
    {
      name: 'groomName',
      label: 'Groom Name',
      type: 'text',
      placeholder: 'e.g., John Doe',
      required: true,
    },
    {
      name: 'groomParentsNames',
      label: 'Groom Parents Names',
      type: 'text',
      placeholder: 'e.g., Mr. and Mrs. Johnson',
      required: true,
    },
    {
      name: 'groomAddress',
      label: 'Groom Address',
      type: 'text',
      placeholder: 'e.g., 123 Main St, City, Country',
      required: true,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, wording...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  outfitDesign: [
    {
      name: 'outfitType',
      label: 'Outfit Type',
      type: 'text',
      placeholder: 'e.g., Bride, Groom, Bridal Party',
      required: false,
    },
    {
      name: 'outfitStyle',
      label: 'Outfit Style',
      type: 'text',
      placeholder: 'e.g., Traditional, Modern, Fusion',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Style preferences, fabric choices...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹150,000',
      required: false,
    },
  ],
  honeymoonPackage: [
    {
      name: 'destination',
      label: 'Destination',
      type: 'text',
      placeholder: 'e.g., Maldives, Switzerland, Bali',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 7 days, 10 days',
      required: false,
    },
    {
      name: 'departureDateTime',
      label: 'Departure Date & Time',
      type: 'datepicker',
      placeholder: 'Select date and time',
      showTimeSelect: true,
      minDate: new Date(),
      dateFormat: 'dd MMM yyyy, h:mm aa',
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Preferences, activities...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹200,000',
      required: false,
    },
  ],
  pandalSetup: [
    {
      name: 'pandalType',
      label: 'Pandal Type',
      type: 'text',
      placeholder: 'e.g., shamiana, fiber sheet, german tent',
      required: true,
    },
    {
      name: 'pandalSize',
      label: 'Pandal Size',
      type: 'text',
      placeholder: 'e.g., 20x30 ft, 40x60 ft',
      required: true,
    },
    {
      name: 'ceilingDecoration',
      label: 'Ceiling Decoration',
      type: 'text',
      placeholder: 'e.g., yes, no, need to check',
      required: false,
    },
    {
      name: 'ceilingDecorationType',
      label: 'Ceiling Decoration Type',
      type: 'text',
      placeholder: 'e.g., fabric draping, fairy lights, chandeliers',
      required: false,
    },
    {
      name: 'ceilingDecorationThemeColor',
      label: 'Ceiling Decoration Theme Color',
      type: 'text',
      placeholder: 'e.g., red, blue, white',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, wording...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  eventFurniture: [
    {
      name: 'furnitureDetails',
      label: 'Furniture Details',
      type: 'array',
      itemLabel: 'Furniture',
      fields: [
        {
          name: 'furnitureType',
          label: 'Furniture Type',
          type: 'text',
          placeholder: 'e.g., tables, chairs, sofas',
          required: true,
        },
        {
          name: 'furnitureStyle',
          label: 'Furniture Style',
          type: 'text',
          placeholder: 'e.g., round-table, armless-chairs, L-shape sofa',
          required: true,
        },
        {
          name: 'furnitureQuantity',
          label: 'Furniture Quantity',
          type: 'text',
          placeholder: 'e.g., 10, 20, 30',
          required: true,
        },
        {
          name: 'furnitureCoverClothColor',
          label: 'Furniture Cover Cloth Color',
          type: 'text',
          placeholder: 'e.g., red, blue, green, n/a',
          required: true,
        },
        {
          name: 'furnitureDecorationOptions',
          label: 'Furniture Decoration Options',
          type: 'text',
          placeholder: 'e.g., floral arrangement, fairy lights, ribbons, sashes, n/a',
          required: true,
        },
      ],
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, wording...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  eventUtensils: [
    {
      name: 'utensilDetails',
      label: 'Utensil Details',
      type: 'array',
      itemLabel: 'Utensil',
      fields: [
        {
          name: 'utensilType',
          label: 'Utensil Type',
          type: 'text',
          placeholder: 'e.g., plates, glasses, cutlery, dessert bowls',
          required: true,
        },
        {
          name: 'utensilStyle',
          label: 'Utensil Style',
          type: 'text',
          placeholder: 'e.g., ceramic plates, crystal glasses, stainless steel cutlery',
          required: true,
        },
        {
          name: 'utensilQuantity',
          label: 'Utensil Quantity',
          type: 'text',
          placeholder: 'e.g., 10, 20, 30',
          required: true,
        },
      ],
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, wording...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
};

export const addOnDetailFields = {
  dj: [
    {
      name: 'djType',
      label: 'DJ Type',
      type: 'text',
      placeholder: 'e.g., Bollywood, EDM, Mix',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 4 hours, Full event',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Music preferences, special requests...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹40,000',
      required: false,
    },
  ],
  activitiesForChildren: [
    {
      name: 'activityType',
      label: 'Activity Type',
      type: 'text',
      placeholder: 'e.g., magic show, puppet show, games',
      required: false,
    },
    {
      name: 'ageGroup',
      label: 'Age Group',
      type: 'text',
      placeholder: 'e.g., 4-8 years, 9-12 years',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 4 hours, Full event',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Activity preferences, special requests...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹40,000',
      required: false,
    },
  ],
  droneCoverage: [
    {
      name: 'droneType',
      label: 'Drone Type',
      type: 'text',
      placeholder: 'e.g., Aerial, Cinematic, Both',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 4 hours, Full event',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Drone preferences, special requests...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹40,000',
      required: false,
    },
  ],
  liveBand: [
    {
      name: 'bandType',
      label: 'Band Type',
      type: 'text',
      placeholder: 'e.g., Classical, Jazz, Rock',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 4 hours, Full event',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Song preferences, band size...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹60,000',
      required: false,
    },
  ],
  liveStreaming: [
    {
      name: 'streamingType',
      label: 'Streaming Type',
      type: 'text',
      placeholder: 'e.g., YouTube, Facebook, Instagram, venue screen',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 4 hours, Full event',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Streaming preferences, special requests...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹60,000',
      required: false,
    },
  ],
  lcdScreens: [
    {
      name: 'numberOfScreens',
      label: 'Number of Screens',
      type: 'text',
      placeholder: 'e.g., 4, 6',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Screen details, timing details...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹15,000',
      required: false,
    },
  ],
  laserLightShow: [
    {
      name: 'showType',
      label: 'Show Type',
      type: 'text',
      placeholder: 'e.g., Laser, LED, Both',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 4 hours, Full event',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Show preferences, special requests...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹40,000',
      required: false,
    },
  ],
  fireworks: [
    {
      name: 'displayType',
      label: 'Display Type',
      type: 'text',
      placeholder: 'e.g., Ground, Aerial, Both',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Safety requirements, timing...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹50,000',
      required: false,
    },
  ],
  photoBooth: [
    {
      name: 'boothType',
      label: 'Booth Type',
      type: 'text',
      placeholder: 'e.g., Classic, 360°, Mirror',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Props, backdrop preferences...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹25,000',
      required: false,
    },
  ],
  welcomeGirls: [
    {
      name: 'numberOfGirls',
      label: 'Number of Girls',
      type: 'text',
      placeholder: 'e.g., 4, 6',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Attire, timing details...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹15,000',
      required: false,
    },
  ],
  welcomeCanvasFrame: [
    {
      name: 'frameSize',
      label: 'Frame Size',
      type: 'text',
      placeholder: 'e.g., 4x6 ft, 6x8 ft',
      required: false,
    },
    {
      name: 'canvasMaterial',
      label: 'Canvas Material',
      type: 'text',
      placeholder: 'e.g., Cotton, Polyester, Blended',
      required: false,
    },
    {
      name: 'decorationOptions',
      label: 'Decoration Options',
      type: 'text',
      placeholder: 'e.g., Floral, Lights, Ribbons',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, timing details...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  welcomeArch: [
    {
      name: 'archType',
      label: 'Arch Type',
      type: 'text',
      placeholder: 'e.g., Arch, Gateway, Floral Structure, Balloon Arch',
      required: false,
    },
    {
      name: 'archShape',
      label: 'Arch Shape',
      type: 'text',
      placeholder: 'e.g., Arch, Square, Custom',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, timing details...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  partyCake: [
    {
      name: 'cakeType',
      label: 'Cake Type',
      type: 'text',
      placeholder: 'e.g., Fondant, Buttercream, Naked Cake',
      required: false,
    },
    {
      name: 'flavor',
      label: 'Flavor',
      type: 'text',
      placeholder: 'e.g., Chocolate, Vanilla, Red Velvet',
      required: false,
    },
    {
      name: 'servings',
      label: 'Number of Servings',
      type: 'text',
      placeholder: 'e.g., 50 servings, 100 servings',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, dietary restrictions...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  bouquetHaram: [
    {
      name: 'flowerType',
      label: 'Flower Type',
      type: 'text',
      placeholder: 'e.g., Roses, Lilies, Orchids',
      required: false,
    },
    {
      name: 'colorScheme',
      label: 'Color Scheme',
      type: 'text',
      placeholder: 'e.g., Red and White, Pastel Colors',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, timing details...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹15,000',
      required: false,
    },
  ],
  valetParking: [
    {
      name: 'numberOfAttendants',
      label: 'Number of Attendants',
      type: 'text',
      placeholder: 'e.g., 2, 4',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Parking area details, duration...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  eventInsurance: [
    {
      name: 'coverageType',
      label: 'Coverage Type',
      type: 'text',
      placeholder: 'e.g., Basic, Comprehensive',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Coverage details, requirements...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹30,000',
      required: false,
    },
  ],
  securityServices: [
    {
      name: 'numberOfGuards',
      label: 'Number of Guards',
      type: 'text',
      placeholder: 'e.g., 4, 6, 8',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Security requirements, timing...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹25,000',
      required: false,
    },
  ],
  socialMediaCoverage: [
    {
      name: 'platforms',
      label: 'Platforms',
      type: 'text',
      placeholder: 'e.g., Instagram, Facebook, Twitter',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Coverage details, hashtags...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹15,000',
      required: false,
    },
  ],
  alcoholLicence: [
    {
      name: 'licenceType',
      label: 'Licence Type',
      type: 'text',
      placeholder: 'e.g., Beer & Wine, Full Bar',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Venue requirements, duration...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹10,000',
      required: false,
    },
  ],
};
