// Configuration for service and addon detail fields
export const serviceDetailFields = {
  stageDecoration: [
    {
      name: 'stageProvidedInVenue',
      label: 'Is stage provided in the venue?',
      type: 'select',
      placeholder: 'Select an option',
      options: [
        { value: 'true', label: 'Yes' },
        { value: 'false', label: 'No' },
        { value: 'needToCheck', label: 'Need to check' },
      ],
    },
    {
      name: 'theme',
      label: 'Theme',
      type: 'select',
      placeholder: 'Select theme',
      options: [
        { value: 'traditional', label: 'Traditional' },
        { value: 'floral', label: 'Floral' },
        { value: 'modern', label: 'Modern' },
        { value: 'balloon', label: 'Balloon' },
        { value: 'mixed', label: 'Mixed' },
      ],
    },
    {
      name: 'decorationPhotos',
      label: 'Select Decoration',
      type: 'gallery-select',
      galleryPath: '/images/decorations',
      helperText: 'Click to select decoration styles from gallery',
      required: false,
    },
    {
      name: 'colorScheme',
      label: 'Color Scheme',
      type: 'text',
      placeholder: 'e.g., Red & Gold, Pink & White',
      required: false,
    },
    {
      name: 'seatingArrangement',
      label: 'Seating Arrangement',
      type: 'select',
      placeholder: 'Select seating arrangement',
      options: [
        { value: 'sofa', label: 'Sofa' },
        { value: 'diwan', label: 'Diwan' },
        { value: 'simhasanam', label: 'Simhasanam' },
        { value: 'oonjal', label: 'Oonjal' },
        { value: 'custom', label: 'Custom' },
      ],
    },
    {
      name: 'numberOfSeats',
      label: 'Number of Seats',
      type: 'select',
      placeholder: 'Select number of seats',
      options: [
        { value: 1, label: '1 seat' },
        { value: 2, label: '2 seats' },
        { value: 3, label: '3 seats' },
        { value: 4, label: '4 seats' },
        { value: 5, label: '5 seats' },
      ],
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Add any specific requirements...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹50,000',
      required: false,
    },
  ],
  catering: [
    {
      name: 'foodServingInVenue',
      label: 'Menu in the venue',
      type: 'cuisine-array',
      cuisineFields: [
        {
          name: 'servingTime',
          label: 'Serving Time',
          type: 'select',
          placeholder: 'Select serving time',
          options: [
            { value: 'breakfast', label: 'Breakfast' },
            { value: 'lunch', label: 'Lunch' },
            { value: 'dinner', label: 'Dinner' },
            { value: 'eveSnack', label: 'Evening Snack' },
            { value: 'brunch', label: 'Brunch' },
            { value: 'hiTea', label: 'Hi-Tea' },
          ],
          required: true,
        },
        {
          name: 'cuisineType',
          label: 'Cuisine Type',
          type: 'select',
          placeholder: 'Select cuisine type',
          options: [
            { value: 'buffet', label: 'Buffet' },
            { value: 'southIndianSadhya', label: 'South Indian Sadhya' },
            { value: 'southIndian', label: 'South Indian Dish' },
            { value: 'northIndianThali', label: 'North Indian Thali' },
            { value: 'northIndian', label: 'North Indian Dish' },
            { value: 'plated', label: 'Plated Service' },
            { value: 'liveCounter', label: 'Live Counter' },
            { value: 'continental', label: 'Continental' },
            { value: 'chinese', label: 'Chinese' },
            { value: 'italianMexican', label: 'Italian/Mexican' },
            { value: 'mixed', label: 'Mixed Cuisine' },
          ],
          required: true,
        },
        {
          menu: [
            {
              name: 'menuItem',
              label: 'Menu Item',
              type: 'text',
              placeholder: 'Dish name',

              required: false,
            },
            {
              name: 'menuItemType',
              label: 'Menu Item Type',
              type: 'select',
              placeholder: 'Type of dish, e.g., appetizer, main course...',
              options: [
                { value: 'appetizer', label: 'Appetizer' },
                { value: 'starter', label: 'Starter' },
                { value: 'mainCourse', label: 'Main Course' },
                { value: 'sideDish', label: 'Side Dish' },
                { value: 'dessert', label: 'Dessert' },
                { value: 'beverage', label: 'Beverage' },
              ],
              required: false,
            },
            {
              name: 'menuItemDiet',
              label: 'Menu Item Diet',
              type: 'select',
              placeholder: 'Diet of dish, e.g., vegetarian, non-vegetarian...',
              options: [
                { value: 'vegetarian', label: 'Vegetarian' },
                { value: 'nonVegetarian', label: 'Non-Vegetarian' },
                { value: 'vegan', label: 'Vegan' },
                { value: 'eggegitarian', label: 'Eggetarian' },
                { value: 'glutenFree', label: 'Gluten-Free' },
                { value: 'dairy', label: 'Dairy' },
              ],
              required: false,
            },
          ],
        },
        {
          name: 'servers',
          label: 'Serving Staff',
          type: 'select',
          placeholder: 'Select serving staff requirement',
          options: [
            { value: 'true', label: 'Yes' },
            { value: 'false', label: 'No' },
          ],
          required: false,
        },
      ],
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Dietary restrictions, menu preferences...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹100,000',
      required: false,
    },
  ],
  transportation: [
    {
      name: 'vehicleDetails',
      label: 'Vehicle Details',
      type: 'vehicle-array',
      vehicleFields: [
        {
          name: 'vehicleType',
          label: 'Vehicle Type',
          type: 'select',
          placeholder: 'Select vehicle type requirement',
          options: [
            { value: 'sedan', label: 'Sedan - up to 5 seats' },
            { value: 'bus', label: 'Bus - up to 40 seats' },
            { value: 'van', label: 'Van - up to 18 seats' },
            { value: 'suv', label: 'SUV - up to 5 seats' },
            { value: 'luxurySedan', label: 'Luxury Sedan Car' },
            { value: 'limousine', label: 'Limousine' },
            { value: 'muv', label: 'MUV - up to 7 seats' },
          ],
          required: false,
        },
        {
          name: 'numberOfVehicles',
          label: 'Number of Vehicles',
          type: 'text',
          placeholder: 'e.g., 2 cars, 1 bus',
          required: false,
        },
        {
          name: 'driverRequired',
          label: 'Driver Required',
          type: 'select',
          placeholder: 'Select driver requirement',
          options: [
            { value: 'true', label: 'Yes' },
            { value: 'false', label: 'No' },
          ],
          required: false,
        },
        {
          name: 'vehiclePickupDropTiming',
          label: 'Vehicle Required Date & Time',
          type: 'datepicker',
          placeholder: 'Select date and time',
          showTimeSelect: true,
          minDate: new Date(),
          dateFormat: 'dd MMM yyyy, h:mm aa',
        },
      ],
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Route details, pickup/drop locations...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹30,000',
      required: false,
    },
  ],
  mehandiHaldi: [
    {
      name: 'ceremonyType',
      label: 'Ceremony Type',
      type: 'text',
      placeholder: 'e.g., Mehandi, Haldi, Both',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Special requirements, timing...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹25,000',
      required: false,
    },
  ],
  photographyVideography: [
    {
      name: 'serviceType',
      label: 'Service Type',
      type: 'text',
      placeholder: 'e.g., Photography, Videography, Both',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., Full day, Half day',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Style preferences, special shots required...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹80,000',
      required: false,
    },
  ],
  saveTheDate: [
    {
      name: 'format',
      label: 'Format',
      type: 'text',
      placeholder: 'e.g., Digital, Printed, Both',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, distribution details...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹10,000',
      required: false,
    },
  ],
  cardDesignPrinting: [
    {
      name: 'cardType',
      label: 'Card Type',
      type: 'text',
      placeholder: 'e.g., Traditional, Modern, Designer',
      required: false,
    },
    {
      name: 'quantity',
      label: 'Quantity',
      type: 'text',
      placeholder: 'e.g., 500 cards',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Design preferences, wording...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  outfitDesign: [
    {
      name: 'outfitType',
      label: 'Outfit Type',
      type: 'text',
      placeholder: 'e.g., Bride, Groom, Bridal Party',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Style preferences, fabric choices...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹150,000',
      required: false,
    },
  ],
  honeymoonPackage: [
    {
      name: 'destination',
      label: 'Destination',
      type: 'text',
      placeholder: 'e.g., Maldives, Switzerland, Bali',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 7 days, 10 days',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Preferences, activities...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹200,000',
      required: false,
    },
  ],
};

export const addOnDetailFields = {
  dj: [
    {
      name: 'djType',
      label: 'DJ Type',
      type: 'text',
      placeholder: 'e.g., Bollywood, EDM, Mix',
      required: false,
    },
    {
      name: 'duration',
      label: 'Duration',
      type: 'text',
      placeholder: 'e.g., 4 hours, Full event',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Music preferences, special requests...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹40,000',
      required: false,
    },
  ],
  liveBand: [
    {
      name: 'bandType',
      label: 'Band Type',
      type: 'text',
      placeholder: 'e.g., Classical, Jazz, Rock',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Song preferences, band size...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹60,000',
      required: false,
    },
  ],
  fireworks: [
    {
      name: 'displayType',
      label: 'Display Type',
      type: 'text',
      placeholder: 'e.g., Ground, Aerial, Both',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Safety requirements, timing...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹50,000',
      required: false,
    },
  ],
  photoBooth: [
    {
      name: 'boothType',
      label: 'Booth Type',
      type: 'text',
      placeholder: 'e.g., Classic, 360°, Mirror',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Props, backdrop preferences...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹25,000',
      required: false,
    },
  ],
  welcomeGirls: [
    {
      name: 'numberOfGirls',
      label: 'Number of Girls',
      type: 'text',
      placeholder: 'e.g., 4, 6',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Attire, timing details...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹15,000',
      required: false,
    },
  ],
  valetParking: [
    {
      name: 'numberOfAttendants',
      label: 'Number of Attendants',
      type: 'text',
      placeholder: 'e.g., 2, 4',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Parking area details, duration...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹20,000',
      required: false,
    },
  ],
  eventInsurance: [
    {
      name: 'coverageType',
      label: 'Coverage Type',
      type: 'text',
      placeholder: 'e.g., Basic, Comprehensive',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Coverage details, requirements...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹30,000',
      required: false,
    },
  ],
  securityServices: [
    {
      name: 'numberOfGuards',
      label: 'Number of Guards',
      type: 'text',
      placeholder: 'e.g., 4, 6, 8',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Security requirements, timing...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹25,000',
      required: false,
    },
  ],
  socialMediaCoverage: [
    {
      name: 'platforms',
      label: 'Platforms',
      type: 'text',
      placeholder: 'e.g., Instagram, Facebook, Twitter',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Coverage details, hashtags...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹15,000',
      required: false,
    },
  ],
  alchoholLicence: [
    {
      name: 'licenceType',
      label: 'Licence Type',
      type: 'text',
      placeholder: 'e.g., Beer & Wine, Full Bar',
      required: false,
    },
    {
      name: 'notes',
      label: 'Additional Notes',
      type: 'textarea',
      placeholder: 'Venue requirements, duration...',
      rows: 3,
      required: false,
    },
    {
      name: 'budget',
      label: 'Budget Estimate',
      type: 'text',
      placeholder: 'e.g., ₹10,000',
      required: false,
    },
  ],
};
